// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9i6c-g66GIt4zzLJFiJ9gtKLnoEi1jZM',
    appId: '1:497277758498:web:429fb8e4aa9d02b220ee7b',
    messagingSenderId: '497277758498',
    projectId: 'chatapp-906fc',
    authDomain: 'chatapp-906fc.firebaseapp.com',
    storageBucket: 'chatapp-906fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVhGhNhSNyv9ftnnRTSEeZ1nyIMViqzZw',
    appId: '1:497277758498:android:0586027b853cdf0920ee7b',
    messagingSenderId: '497277758498',
    projectId: 'chatapp-906fc',
    storageBucket: 'chatapp-906fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfgGRCBJP2uGEbf5DNU3hjUOP18S8vam8',
    appId: '1:497277758498:ios:adccba5dfb1ecba820ee7b',
    messagingSenderId: '497277758498',
    projectId: 'chatapp-906fc',
    storageBucket: 'chatapp-906fc.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfgGRCBJP2uGEbf5DNU3hjUOP18S8vam8',
    appId: '1:497277758498:ios:adccba5dfb1ecba820ee7b',
    messagingSenderId: '497277758498',
    projectId: 'chatapp-906fc',
    storageBucket: 'chatapp-906fc.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9i6c-g66GIt4zzLJFiJ9gtKLnoEi1jZM',
    appId: '1:497277758498:web:8bdaa3f52e6d66ea20ee7b',
    messagingSenderId: '497277758498',
    projectId: 'chatapp-906fc',
    authDomain: 'chatapp-906fc.firebaseapp.com',
    storageBucket: 'chatapp-906fc.firebasestorage.app',
  );
}
